version: "3.8"

services:
  proxy:
    image: nginx:1.19-alpine
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
      - redis
  frontend:
    image: 23-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
  backend:
    image: 23-backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  redis:
    image: redis:alpine
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    container_name: db_psql
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
