version: "3.8"

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service:ubuntu
    build: .
    volumes:
      - ./text.log:/usr/src/app/text.log
    ports:
      - 8080:8080
    command:
      - server
