version: "3.8"

services:
  frontend:
    build: ./frontend/.
    ports:
      - 5001:5001
  backend:
    build: ./backend/.
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
